Amr Logical Agent Implementation
iml130/sola pull request #23
Opened 2023-06-15 09:49 UTC by janagoe

Closes #11

# Proposed Changes
Implementing the AmrLogicalAgent based on the LogicalAgent interface

# Definition of Done (optional)
- [ ] Feature is implemented
- [ ] No known bugs that stops the correct execution
- [ ] CI / CD pipeline passed
- [ ] The code guidelines were followed
- [ ] Unit and / or Integration tests for the new feature
- [ ] New feature was added to the documentation

2023-06-15 12:17 UTC, ltoenning requested changes

2023-06-15 12:17 UTC, ltoenning commented on daisi/src/cpps/logical/amr/amr_logical_agent.cpp
> +  socket_of_physical_->GetSockName(logical_address);
Maybe a typo. To get the address of the logical, this should be the listening socket.

2023-06-15 12:17 UTC, ltoenning commented on third_party/Catch2
This is a downgrade from v3.3.2 to v3.2.1. Is this intentional? :smile:

2023-06-15 12:17 UTC, ltoenning commented on solanet/third_party/cereal
This is a version upgrade. Is this intentional?

2023-06-16 06:47 UTC, tseeland commented on daisi/src/cpps/logical/amr/amr_logical_agent.cpp
> +  checkSendingNextTask();
Will you send the next task if the previous task is not finished yet? `AmrStatusUpdate` does not send information about the task.

2023-06-16 06:47 UTC, tseeland commented on daisi/src/cpps/logical/amr/amr_logical_agent.cpp
> +  checkSendingNextTask();
Will you send the next task if the previous task is not finished yet? `AmrStatusUpdate` does not send information about the task.

2023-06-16 07:02 UTC, tseeland reviewed
All in all just minor questions. Folder structure is another issue for another time.

2023-06-16 07:36 UTC, tseeland approved these changes

2023-06-16 07:40 UTC, tseeland approved these changes
Nothing changed since last approval.

2023-06-16 09:57 UTC, ltoenning approved these changes

2023-06-16 10:36 UTC, merged