Autonomous Mobile Robots Documentation
iml130/sola pull request #46
Opened 2023-07-17 10:34 UTC by tseeland

2023-07-17 12:54 UTC, ptrdtznr requested changes
From my point of view, the documentation requires further information before the documentation can be merged. As internally mentioned, an outline would be here beneficial

2023-07-17 12:54 UTC, ptrdtznr commented on applications/docs/glossary.md
- In order to be able to track changes over a long time, it is recommended to have line break after each sentence.
- I would not start to discuss the differences of AMRs and AGVs. Many people have different opinions about that. In case you think you *must* have a definition, please get a proper reference to get further information
- Material Flow and Transport Order is missing

2023-08-16 13:55 UTC, ltoenning approved these changes

2023-08-16 14:26 UTC, ptrdtznr commented
approved ;)

2023-08-16 14:27 UTC, merged